configure:
  languages:
    go: true
  plugins:
    - .aspect/cli/go_image.star
lint:
  aspects:

plugins:
    - name: fix-visibility
      from: github.com/aspect-build/plugin-fix-visibility
      version: v0.1.0
