load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "hello_lib",
    srcs = ["main.go"],
    importpath = "github.com/example/project/cowsay/cmd/hello",
    visibility = ["//visibility:private"],
    deps = ["@io_nmyk_cowsay//:cowsay"],
)

go_binary(
    name = "hello",
    embed = [":hello_lib"],
    visibility = ["//visibility:public"],
)
